use std::fs::File;
use std::io::Read;
use std::path::Path;
use std::process::Command;

use crate::package::Package;

pub fn load_packages() -> Vec<Package> {
    let path = "packages.json";
    if Path::new(path).exists() {
        let mut file = File::open(path).unwrap();
        let mut contents = String::new();
        file.read_to_string(&mut contents).unwrap();
        serde_json::from_str(&contents).unwrap_or_else(|_| default_packages())
    } else {
        default_packages()
    }
}

fn default_packages() -> Vec<Package> {
    vec![
        Package {
            name: "GIMP".to_string(),
            description: "Potężny edytor graficzny do tworzenia i edycji obrazów. Obsługuje warstwy, maski i zaawansowane narzędzia edycji.".to_string(),
            icon: "https://www.gimp.org/images/frontpage/wilber-big.png".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install gimp".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove gimp".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q gimp".to_string(),
        },
        Package {
            name: "VLC".to_string(),
            description: "Wszechstronny odtwarzacz multimedialny obsługujący wiele formatów audio i video bez dodatkowych kodeków.".to_string(),
            icon: "https://www.videolan.org/images/logo.png".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install vlc vlc-codecs".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove vlc vlc-codecs".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q vlc".to_string(),
        },
        Package {
            name: "Firefox".to_string(),
            description: "Szybka i prywatna przeglądarka internetowa z zaawansowanymi funkcjami ochrony prywatności.".to_string(),
            icon: "https://www.mozilla.org/media/protocol/img/logos/firefox/browser/logo.eb1324e44442.svg".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install MozillaFirefox".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove MozillaFirefox".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q MozillaFirefox".to_string(),
        },
        Package {
            name: "LibreOffice".to_string(),
            description: "Kompletny pakiet biurowy zawierający edytor tekstu, arkusze kalkulacyjne, prezentacje i wiele więcej.".to_string(),
            icon: "https://www.libreoffice.org/assets/Uploads/LibreOffice-Initial-Artwork-Icons/LibreOffice-Initial-Artwork-Icons-64px.png".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install libreoffice".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove libreoffice".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q libreoffice".to_string(),
        },
        Package {
            name: "Krita".to_string(),
            description: "Zaawansowany edytor graficzny dla artystów cyfrowych, świetny do malarstwa i ilustracji.".to_string(),
            icon: "https://krita.org/wp-content/uploads/2022/02/krita_logo_300x300.png".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install krita".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove krita".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q krita".to_string(),
        },
        Package {
            name: "OBS Studio".to_string(),
            description: "Oprogramowanie do nagrywania ekranu i streamingu na żywo.".to_string(),
            icon: "https://obsproject.com/assets/images/new_icon_small-r.png".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install obs-studio".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove obs-studio".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q obs-studio".to_string(),
        },
        Package {
            name: "Steam".to_string(),
            description: "Platforma do gier i zarządzania biblioteką gier komputerowych.".to_string(),
            icon: "https://store.cloudflare.steamstatic.com/public/shared/images/header/logo_steam.svg".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install steam".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove steam".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q steam".to_string(),
        },
        Package {
            name: "Discord".to_string(),
            description: "Aplikacja do komunikacji głosowej, wideo i czatów tekstowych dla graczy i społeczności.".to_string(),
            icon: "https://cdn.worldvectorlogo.com/logos/discord-6.svg".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install discord".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove discord".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q discord".to_string(),
        },
        Package {
            name: "Chromium".to_string(),
            description: "Otwartoźródłowa wersja przeglądarki Google Chrome.".to_string(),
            icon: "https://upload.wikimedia.org/wikipedia/commons/8/87/Chromium_Logo.svg".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install chromium".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove chromium".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q chromium".to_string(),
        },
        Package {
            name: "Kdenlive".to_string(),
            description: "Profesjonalny edytor wideo typu open-source z obsługą wielu formatów i efektów.".to_string(),
            icon: "https://kdenlive.org/wp-content/uploads/kdenlive-logo-300x300.png".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install kdenlive".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove kdenlive".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q kdenlive".to_string(),
        },
        Package {
            name: "Inkscape".to_string(),
            description: "Edytor grafiki wektorowej do tworzenia ilustracji i logotypów.".to_string(),
            icon: "https://media.inkscape.org/static/images/inkscape-logo.svg".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install inkscape".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove inkscape".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q inkscape".to_string(),
        },
        Package {
            name: "Audacity".to_string(),
            description: "Popularny edytor audio z obsługą wielu efektów i nagrywania wielościeżkowego.".to_string(),
            icon: "https://upload.wikimedia.org/wikipedia/commons/0/0d/Audacity_Logo.svg".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install audacity".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove audacity".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q audacity".to_string(),
        },
        Package {
            name: "Thunderbird".to_string(),
            description: "Klient pocztowy z obsługą wielu kont, kalendarza i wtyczek.".to_string(),
            icon: "https://www.thunderbird.net/media/img/thunderbird/thunderbird-256.png".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install MozillaThunderbird".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove MozillaThunderbird".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q MozillaThunderbird".to_string(),
        },
        Package {
            name: "VirtualBox".to_string(),
            description: "Oprogramowanie do wirtualizacji, umożliwiające uruchamianie wielu systemów operacyjnych.".to_string(),
            icon: "https://www.virtualbox.org/graphics/vbox_logo2_gradient.png".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install virtualbox".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove virtualbox".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q virtualbox".to_string(),
        },
        Package {
            name: "Blender".to_string(),
            description: "Wolne i otwarte oprogramowanie do tworzenia grafiki 3D, animacji i renderingu.".to_string(),
            icon: "https://www.blender.org/wp-content/uploads/2019/07/Blender_logo_no_text.svg".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install blender".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove blender".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q blender".to_string(),
        },
        Package {
            name: "Visual Studio Code".to_string(),
            description: "Edytor kodu zoptymalizowany do budowania i debugowania nowoczesnych aplikacji webowych i chmurowych.".to_string(),
            icon: "https://code.visualstudio.com/assets/images/code-stable.png".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install code".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove code".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q code".to_string(),
        },
        Package {
            name: "Telegram Desktop".to_string(),
            description: "Aplikacja desktopowa do komunikacji tekstowej, głosowej i wideo.".to_string(),
            icon: "https://telegram.org/img/t_logo.png".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install telegram-desktop".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove telegram-desktop".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q telegram-desktop".to_string(),
        },
        Package {
            name: "GParted".to_string(),
            description: "Edytor partycji dyskowych dla GNOME.".to_string(),
            icon: "https://gparted.org/images/gparted-128.png".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install gparted".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove gparted".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q gparted".to_string(),
        },
        Package {
            name: "FileZilla".to_string(),
            description: "Klient FTP do przesyłania plików.".to_string(),
            icon: "https://filezilla-project.org/images/filezilla_128x128.png".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install filezilla".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove filezilla".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q filezilla".to_string(),
        },
        Package {
            name: "Darktable".to_string(),
            description: "Otwartoźródłowa aplikacja do obróbki zdjęć RAW.".to_string(),
            icon: "https://www.darktable.org/resources/darktable.svg".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install darktable".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove darktable".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q darktable".to_string(),
        },
        Package {
            name: "Calibre".to_string(),
            description: "Menedżer e-booków do organizacji i konwersji książek elektronicznych.".to_string(),
            icon: "https://calibre-ebook.com/img/calibre.svg".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install calibre".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove calibre".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q calibre".to_string(),
        },
        Package {
            name: "Flameshot".to_string(),
            description: "Potężne, ale proste narzędzie do robienia zrzutów ekranu.".to_string(),
            icon: "https://flameshot.org/img/flameshot-logo.png".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install flameshot".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove flameshot".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q flameshot".to_string(),
        },
        Package {
            name: "Remmina".to_string(),
            description: "Klient do zdalnego pulpitu obsługujący RDP, VNC i inne protokoły.".to_string(),
            icon: "https://remmina.org/wp-content/uploads/2017/02/remmina-icon-256.png".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install remmina".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove remmina".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q remmina".to_string(),
        },
        Package {
            name: "Vim".to_string(),
            description: "Zaawansowany edytor tekstu dla programistów i administratorów.".to_string(),
            icon: "https://www.vim.org/images/vim_small.gif".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install vim".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove vim".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q vim".to_string(),
        },
        Package {
            name: "Git".to_string(),
            description: "System kontroli wersji do zarządzania kodem źródłowym.".to_string(),
            icon: "https://git-scm.com/images/logos/downloads/Git-Icon-1788C.png".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install git".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove git".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q git".to_string(),
        },
        Package {
            name: "Node.js".to_string(),
            description: "Środowisko uruchomieniowe JavaScript do budowania aplikacji serwerowych.".to_string(),
            icon: "https://nodejs.org/static/images/logo.svg".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install nodejs".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove nodejs".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q nodejs".to_string(),
        },
        Package {
            name: "Python".to_string(),
            description: "Język programowania wysokiego poziomu z bogatą biblioteką standardową.".to_string(),
            icon: "https://www.python.org/static/img/python-logo.png".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install python3".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove python3".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q python3".to_string(),
        },
        Package {
            name: "Spotify".to_string(),
            description: "Aplikacja do strumieniowania muzyki.".to_string(),
            icon: "https://www.spotify.com/us/assets/spotify-for-artists.png".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install spotify".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove spotify".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q spotify".to_string(),
        },
        Package {
            name: "Eclipse".to_string(),
            description: "IDE do programowania w Java i innych językach.".to_string(),
            icon: "https://www.eclipse.org/downloads/images/eclipse-ide-logo.png".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install eclipse".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove eclipse".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q eclipse".to_string(),
        },
        // Dodane dodatkowe aplikacje
        Package {
            name: "VSCode".to_string(),
            description: "Popularny edytor kodu z wieloma rozszerzeniami.".to_string(),
            icon: "https://code.visualstudio.com/assets/images/code-stable.png".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install code".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove code".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q code".to_string(),
        },
        Package {
            name: "IntelliJ IDEA".to_string(),
            description: "IDE dla Java i innych języków programowania.".to_string(),
            icon: "https://www.jetbrains.com/company/brand/img/logos/intellij_idea.png".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install intellij-idea-community".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove intellij-idea-community".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q intellij-idea-community".to_string(),
        },
        Package {
            name: "Postman".to_string(),
            description: "Narzędzie do testowania API.".to_string(),
            icon: "https://www.postman.com/assets/logos/postman-logo-stacked.svg".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install postman".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove postman".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q postman".to_string(),
        },
        Package {
            name: "Docker".to_string(),
            description: "Platforma do konteneryzacji aplikacji.".to_string(),
            icon: "https://www.docker.com/wp-content/uploads/2022/03/Moby-logo.png".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install docker".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove docker".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q docker".to_string(),
        },
        Package {
            name: "Kubernetes".to_string(),
            description: "System orkiestracji kontenerów.".to_string(),
            icon: "https://kubernetes.io/images/kubernetes-logo.svg".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install kubectl".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove kubectl".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q kubectl".to_string(),
        },
        Package {
            name: "MySQL".to_string(),
            description: "System zarządzania bazami danych.".to_string(),
            icon: "https://www.mysql.com/common/logos/logo-mysql-170x115.png".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install mysql".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove mysql".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q mysql".to_string(),
        },
        Package {
            name: "PostgreSQL".to_string(),
            description: "Zaawansowany system zarządzania bazami danych.".to_string(),
            icon: "https://www.postgresql.org/media/img/about/press/elephant.png".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install postgresql".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove postgresql".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q postgresql".to_string(),
        },
        Package {
            name: "Redis".to_string(),
            description: "Baza danych klucz-wartość w pamięci.".to_string(),
            icon: "https://redis.io/images/redis-white.png".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install redis".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove redis".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q redis".to_string(),
        },
        Package {
            name: "MongoDB".to_string(),
            description: "NoSQL baza danych zorientowana na dokumenty.".to_string(),
            icon: "https://www.mongodb.com/assets/images/global/favicon.ico".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install mongodb".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove mongodb".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q mongodb".to_string(),
        },
        Package {
            name: "Apache HTTP Server".to_string(),
            description: "Serwer WWW open-source.".to_string(),
            icon: "https://httpd.apache.org/images/httpd_logo_wide_new.png".to_string(),
            install_command: "sudo /usr/lib/legendaryos/rpm-ostree install httpd".to_string(),
            remove_command: "sudo /usr/lib/legendaryos/rpm-ostree remove httpd".to_string(),
            update_command: "sudo /usr/lib/legendaryos/rpm-ostree upgrade".to_string(),
            check_command: "rpm -q httpd".to_string(),
        },
    ]
}

pub fn is_package_installed(check_command: &str) -> bool {
    Command::new("sh")
        .arg("-c")
        .arg(check_command)
        .output()
        .map(|output| output.status.success())
        .unwrap_or(false)
}
